# Generated by Django 4.1.3 on 2022-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionedapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='logo_url',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
